swagger: "2.0"
info:
  version: 1.0.0
  title: kijiji
  description: Kijiji Scraper
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

  SearchBody:
    type: object
    title: search
    required:
      - key
    properties:
      key:
        type: string
        example: plateau
      isMatched:
        type: boolean
        example: false
      createdAt:
        type: string
        format: date-time
      lastMatch:
        type: string
        format: date-time

paths:
  /searches:
    get:
      tags:
        - Searches
      description: Fetch all Searches
      responses:
        200:
          description: Returns all Searches
    post:
      tags:
        - Searches
      description: Create a new Searches
      parameters:
        - name: search
          in: body
          description: a search
          required: true
          schema:
            $ref: "#/definitions/SearchBody"
      responses:
        201:
          description: Returns created Search

  /searches/{key}:
    get:
      tags:
        - Searches
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the search to retrieve
          type: string
      responses:
        200:
          description: Return the search with the specified key
        404:
          description: Search not found
    delete:
      tags:
        - Searches
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the search to retrieve
          type: string
      responses:
        202:
          description: Search Deleted
        404:
          description: Search not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification