swagger: "2.0"
info:
  version: 1.0.0
  title: kijiji
  description: Kijiji Scraper
basePath: /api/v1
tags:
  - name: Searches
    description: Searches endpoint
  - name: Specification
    description: The swagger API specification

consumes:
  - application/json
produces:
  - application/json


definitions:

  SearchCreate:
    allOf:
      - $ref: "#/definitions/Search"
    title: SearchCreate
    required:
      - key
    properties:
      key:
        type: string
        example: plateau
        readOnly: false

  KijijiSearchCreate:
    allOf:
      - $ref: "#/definitions/KijijiSearch"
      - $ref: "#/definitions/SearchCreate"
    title: KijijiSearchCreate
        
  Search:
    title: SearchObject
    properties:
      cronRule:
        type: string
        pattern: '^(\*|([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])|\*\/([0-9]|1[0-9]|2[0-9]|3[0-9]|4[0-9]|5[0-9])) (\*|([0-9]|1[0-9]|2[0-3])|\*\/([0-9]|1[0-9]|2[0-3])) (\*|([1-9]|1[0-9]|2[0-9]|3[0-1])|\*\/([1-9]|1[0-9]|2[0-9]|3[0-1])) (\*|([1-9]|1[0-2])|\*\/([1-9]|1[0-2])) (\*|([0-6])|\*\/([0-6]))$'
        example: '0 */2 * * *'
      bodyRegex:
        type: string
        example: '(condo|dishwasher)'
      key:
        type: string
        example: plateau
        readOnly: true
      isMatched:
        type: boolean
        example: false
        readOnly: true
      createdAt:
        type: string
        format: date-time
        readOnly: true
      lastMatch:
        type: string
        format: date-time
        readOnly: true

  KijijiSearch:
    allOf:
      - $ref: "#/definitions/Search"
    title: KijijiSearch
    properties:
      locationId:
        type: number
        example: 1
      categoryId:
        type: number
        example: 1

paths:
  /searches/kijiji:
    get:
      tags:
        - Searches
      description: Fetch all Searches
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/KijijiSearch"
    post:
      tags:
        - Searches
      description: Create a new Search
      parameters:
        - name: body
          in: body
          description: a search
          required: true
          schema:
            $ref: "#/definitions/KijijiSearchCreate"
      responses:
        201:
          description: Returns created Search
          schema:
            $ref: "#/definitions/KijijiSearch"
        422:
          description: Validation error

  /searches/kijiji/categories:
    get:
      tags:
        - Searches
      description: Fetch all Available Categories and their ID
      responses:
        200:
          description: "successful operation"

  /searches/kijiji/locations:
    get:
      tags:
        - Searches
      description: Fetch all Available locations and their ID
      responses:
        200:
          description: "successful operation"

  /searches/kijiji/{key}:
    parameters:
      - name: provider
        in: path
        required: true
        description: Search Provider
        type: string
        enum: [kijiji]
    get:
      tags:
        - Searches
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the search to retrieve
          type: string
      responses:
        200:
          description: Return the search with the specified key
          schema:
            $ref: "#/definitions/KijijiSearch"
        404:
          description: Search not found
    put:
      tags:
        - Searches
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the search to update
          type: string
        - name: body
          in: body
          description: a search
          required: true
          schema:
            $ref: "#/definitions/KijijiSearch"
      responses:
        200:
          description: Return the updated search
          schema:
            $ref: "#/definitions/KijijiSearch"
        404:
          description: Search not found
    delete:
      tags:
        - Searches
      parameters:
        - name: key
          in: path
          required: true
          description: The key of the search to retrieve
          type: string
      responses:
        202:
          description: Search Deleted
        404:
          description: Search not found

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification